Hello.class : Hello.java
	@javac Hello.java

test_hello : Hello.class
	@java Hello

Exercise.class : Exercise.java
	@javac Exercise.java

test_exercise : Exercise.class
	@java Exercise

clean :
	rm *.class
